name: test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install testing dependencies
        run: |
          pip install toml==0.10.2
      - name: Install package dependencies
        # We use this roundabout dependency installation to avoid inadvertently
        # adding poetry sub-dependencies
        run: |
          python scripts/get_required_deps.py | pip install -r /dev/stdin
      - name: Run unit tests
        run: |
          make ci_unit_tests
